version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000' # Publicly accessible for the API
    env_file: .env
    depends_on:
      redis:
        condition: service_healthy
      mongo:
        condition: service_healthy
    restart: unless-stopped

  worker:
    build: .
    command: npm run worker
    env_file: .env
    depends_on:
      redis:
        condition: service_healthy
      mongo:
        condition: service_healthy
    restart: unless-stopped

  redis:
    image: redis
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017 --quiet
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-data:
